### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '/C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master/files

### ISSUE THREAD

**Issue by xivok** [Lunik/tcloud#111]
[26/05/2019 14:26:11] [Info]    [File] Creating /C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master/files
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir '/C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master/files'
    at Object.mkdirSync (fs.js:773:3)
    at t.value (C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:6116)
    at Object.<anonymous> (C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:18781)
    at t (C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:101)
    at new e (C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:11292)
    at t.<anonymous> (C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:10344)
    at t.emit (events.js:193:13)
    at C:\Users\Lenovo\Desktop\tcloud-master\tcloud-master\server.js:1:2331
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)

**Comment by itsecres-nandant** [comment]
same issue here:

Error: ENOENT: no such file or directory, mkdir 'C:\C:\NPM\TCLOUD\tcloud-v0.8.7\files'
