### ISSUE TITLE
Error with config when deploying with OpenShift

### ISSUE THREAD

**Issue by nk932714** [Lunik/tcloud#62]
I'm am trying to deploy your application on OpenShift but I get this error.
Can you please figured out what is going on ?

### Stack trace:
```
error log :======== 

[13/10/2017 04:00:28] [Error]	[Config] SyntaxError: Unexpected end of JSON input
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at t.value (/usr/src/app/server.js:1:2397)
    at /usr/src/app/server.js:1:2098
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)
```

**Comment by Lunik** [comment]
First, what version are you using.
Can you provide me steps to reproduce the issue ?

**Comment by nk932714** [comment]
**steps to reproduce** 

1) Login to openshift
2) create project name / add a project
3) click on deploy image & click on enter the image name(docker image name) ( i entered " lunik/tcloud " ) and click on search 
![image](https://user-images.githubusercontent.com/29853208/31542389-6b8690c8-b02f-11e7-9f7e-d932a0a55a9b.png)

4) click on create 
Now check the logs
